name: Tests

on:
  pull_request:
    branches:
      - develop
      - master

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-versions: ['7.4', '8.0', '8.1', '8.2', '8.3']

    steps:
      - uses: actions/checkout@v4

      - name: Cache composer dependencies
        uses: actions/cache@v4
        with:
          path: vendor
          key: composer-${{ hashFiles('composer.lock') }}

      - name: Setup PHP
        uses: shivammathur/setup-php@master
        with:
          php-version: ${{ matrix.php-versions }}
          coverage: none
          extensions: mysql
          tools: composer:v2, phpunit:v9

      - name: Run composer install
        run: composer install -n --prefer-dist

      - name: PHPUnit Tests
        run: phpunit --coverage-text
